//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsGroup
    {
        public int GroupID { get; set; }
        public int AssetsID { get; set; }
        public Nullable<int> Assigned { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual GroupT GroupT { get; set; }
    }
}
