//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downloads
    {
        public System.Guid ID { get; set; }
        public int FileID { get; set; }
        public int RequesterID { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public System.DateTime DateTimeExpire { get; set; }
        public Nullable<int> DownloadsMade { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Requesters Requesters { get; set; }
    }
}
