//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public System.Guid ID { get; set; }
        public int GroupID { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public string AccessNumber { get; set; }
    }
}
