//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requesters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requesters()
        {
            this.Downloads = new HashSet<Downloads>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surnames { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int CountryID { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string Intitution { get; set; }
        public string InstitutionType { get; set; }
        public string ReferencedBy { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> SubscriptionAuthorized { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downloads> Downloads { get; set; }
        public virtual Level Level { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
